const ColorSchemes = {
  normal: {
    button_border_radius: "1000px",
    header_bg: "white",
    main_bg: "rgb(236, 236, 236)",
    main_top_bar_bg: "white",
    main_bottom_top_border: "transparent",
    main_bottom_top_border_sz: "0px",
    main_controls_bg: "white",
    success_green: "rgb(23, 187, 119)",
    success_green_border: "transparent",
    success_green_border_sz: "0px",
    negative_grey: "#e2e2e2",
    negative_grey_border: "transparent",
    quit_border_sz: "1px",
    grey1: "rgb(196, 196, 196)",
    report_button_bg: "#1379A1",
    report_button_border: "transparent",
    report_button_border_sz: "2px",
    text_dark: "#444444",
    text_dark2: "#333333",
    text_light: "white",
    shadow1: "rgba(0, 0, 0, 0.2)",
    shadow2: "rgba(0, 0, 0, 0.15)",
    link_color: "blue",

    notification_bg: "white",
    notification_border: "transparent",
    notification_border_sz: "0px",
    notification_border_radius: "5px",
    notification_color: "#333333",

    nav_color: "#333333",
    nav_bg: "transparent",
    nav_border_sz: "0px",
    nav_border: "transparent",

    scrollbar_thumb_bg: "white",
    scrollbar_thumb_hover: "#c7c7c7",
    scrollbar_track: "#e9e9e9",
    scrollbar_track_border: "rgba(0, 0, 0, 0.2)",
    scrollbar_track_border_sz: "1px",

    search_bg: "white",
    search_color: "#333333",
    search_placeholder: "#555555",
    search_border: "rgba(0, 0, 0, 0.3)",
    search_border_sz: "1px",
    search_border_radius: "5px",

    tile_bg: "white",
    tile_border: "rgba(0, 0, 0, 0.2)",
    tile_border_size: "1px",
    tile_sex_bg: "rgb(223, 223, 223)",
    tile_sex_text_selected: "black",
    tile_sex_bg_selected: "rgb(190, 190, 190)",
    tile_content_bg: "white",
    tile_count_bg: "#037789",
    tile_count_border: "transparent",
    tile_count_border_sz: "0px",

    popup_background: "rgba(0, 0, 0, 0.6)",
    popup_bg: "white",
    popup_border: "transparent",
    popup_border_sz: "0px",
    popup_h1: "rgb(50, 50, 50)",
    popup_negative_bg: "#e2e2e2",
    popup_negative_color: "rgb(41, 41, 41)",
    popup_negative_border: "rgba(0, 0, 0, 0.15)",
    popup_negative_border_sz: "1px",
    popup_positive_bg: "#3a98af",
    popup_positive_color: "white",
    popup_positive_border: "transparent",
    popup_positive_border_sz: "0px",
    popup_positive_shadow: "rgba(0, 0, 0, 0.2)",

    count_button_color: "white",
    count_button_bg: "rgb(73, 178, 185)",
    count_button_border: "transparent",
    count_button_border_sz: "0px",
    count_button_hover_bg: "rgb(59, 120, 145)",
    count_sc_bg: "rgb(223, 223, 223)",
    count_sc_color: "#383838",
    count_sc_sel_bg: "rgb(190, 190, 190)",
    count_sc_sel_color: "#272727",

    input_title: "rgb(50, 50, 50)",
    input_bg: "white",
    input_color: "#444",
    input_border: "#bbbbbb",
    input_border_sz: "1px",
    input_border_radius: "5px",

    error_mesage: "#4d4d4d",
    form_title: "rgb(50, 50, 50)",
    form_bg: "white",
    form_border: "transparent",
    form_border_sz: "0px",
    form_border_radius: "16px",
    form_shadow: "rgba(0, 0, 0, 0.1)",
    form_submit_bg: "#3a98af",
    form_submit_color: "white",
    form_submit_shadow: "rgba(0, 0, 0, 0.2)",
    form_submit_border: "transparent",
    form_submit_border_sz: "0px",

    manual_enter_bg: "#e2e2e2",
    manual_enter_color: "#2c2c2c",
    manual_enter_border: "rgba(0, 0, 0, 0.15)",
    manual_enter_border_sz: "1px",
    manual_enter_border_radius: "10px",

    address_list_color: "#333333",
    address_list_bg: "#f7f7f7",
    address_list_border: "rgba(0, 0, 0, 0.3)",
    address_list_border_sz: "1px",
    address_hover_bg: "#dfdfdf",
  },
  high_contrast: {
    button_border_radius: "0px",
    header_bg: "black",
    main_bg: "black",
    main_top_bar_bg: "black",
    main_bottom_top_border: "blueviolet",
    main_bottom_top_border_sz: "3px",
    main_controls_bg: "black",
    success_green: "black",
    success_green_border: "white",
    success_green_border_sz: "2px",
    negative_grey: "#e2e2e2",
    negative_grey_border: "white",
    grey1: "black",
    quit_border_sz: "2px",
    report_button_bg: "black",
    report_button_border: "white",
    report_button_border_sz: "2px",
    text_dark: "white",
    text_dark2: "white",
    text_light: "white",
    shadow1: "transparent",
    shadow2: "transparent",
    link_color: "yellow",

    notification_bg: "black",
    notification_border: "blue",
    notification_border_sz: "3px",
    notification_border_radius: "0px",
    notification_color: "white",

    nav_color: "yellow",
    nav_bg: "black",
    nav_border_sz: "2px",
    nav_border: "yellow",

    scrollbar_thumb_bg: "yellow",
    scrollbar_thumb_hover: "blueviolet",
    scrollbar_track: "black",
    scrollbar_track_border: "yellow",
    scrollbar_track_border_sz: "2px",

    search_bg: "black",
    search_color: "white",
    search_placeholder: "white",
    search_border: "yellow",
    search_border_sz: "2px",
    search_border_radius: "0px",

    tile_bg: "black",
    tile_border: "blue",
    tile_border_size: "3px",
    tile_sex_bg: "black",
    tile_sex_text_selected: "black",
    tile_sex_bg_selected: "yellow",
    tile_content_bg: "black",
    tile_count_bg: "black",
    tile_count_border: "blue",
    tile_count_border_sz: "3px",

    popup_background: "black",
    popup_bg: "black",
    popup_h1: "white",
    popup_border: "blue",
    popup_border_sz: "3px",
    popup_negative_bg: "black",
    popup_negative_color: "white",
    popup_negative_border: "white",
    popup_negative_border_sz: "0px",
    popup_positive_bg: "black",
    popup_positive_color: "white",
    popup_positive_border: "white",
    popup_positive_border_sz: "2px",
    popup_positive_shadow: "transparent",

    count_button_color: "black",
    count_button_bg: "yellow",
    count_button_border: "yellow",
    count_button_border_sz: "3px",
    count_button_hover_bg: "blueviolet",
    count_sc_bg: "black",
    count_sc_color: "white",
    count_sc_sel_bg: "yellow",
    count_sc_sel_color: "black",

    input_title: "white",
    input_bg: "black",
    input_color: "white",
    input_border: "yellow",
    input_border_sz: "2px",
    input_border_radius: "0",

    error_mesage: "white",
    form_title: "white",
    form_bg: "black",
    form_border: "blue",
    form_border_sz: "5px",
    form_border_radius: "0px",
    form_shadow: "rgba(0, 0, 0, 0.1)",
    form_submit_bg: "black",
    form_submit_color: "white",
    form_submit_shadow: "transparent",
    form_submit_border: "white",
    form_submit_border_sz: "2px",

    manual_enter_bg: "black",
    manual_enter_color: "white",
    manual_enter_border: "white",
    manual_enter_border_sz: "2px",
    manual_enter_border_radius: "0px",

    address_list_color: "white",
    address_list_bg: "blue",
    address_list_border: "yellow",
    address_list_border_sz: "2px",
    address_hover_bg: "purple",
  },
};

export default ColorSchemes;
